# Generated by Django 4.0.7 on 2023-05-25 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryImage', models.ImageField(upload_to='subCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodSubCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('subCategoryName', models.CharField(max_length=100)),
                ('subCategoryImage', models.ImageField(upload_to='subCategory')),
                ('foodCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodSubCategory', to='foodStuff.foodcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('foodName', models.CharField(max_length=100)),
                ('foodProductDescription', models.TextField()),
                ('foodPrice', models.IntegerField()),
                ('foodProductImage', models.ImageField(upload_to='foodProduct')),
                ('foodCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodCategory', to='foodStuff.foodcategory')),
                ('foodSubCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodSubCategory', to='foodStuff.foodsubcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodQuantity', models.PositiveIntegerField()),
                ('foodPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foodProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodCart', to='foodStuff.foodproduct')),
            ],
        ),
    ]
