# Generated by Django 4.0.7 on 2023-05-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodStuff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCart',
        ),
    ]
